version: "3.7"

services:
  bot:
    build:
      context: .
    working_dir: /app
    command: "python src/bot/bot.py"
    env_file:
      - .env
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure

  db:
    image: postgres:latest
    command: postgres -c 'max_connections=999'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql-data-test:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  admin_panel:
    build:
      context: .
    working_dir: /app
    command: "python src/admin_panel/app.py"
    env_file:
      - .env
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure


volumes:
  postgresql-data-test: